---
version: '2'

run:
  timeout: 3m
  skip-dirs:
    - example_files

linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - style
    - test
    - unused
  disable:
    - depguard
    - forcetypeassert
    - exhaustruct
    - gochecknoglobals
