---
version: "2"

run:
  timeout: 3m

linters:
  disable:
    - depguard
    - forcetypeassert
    - exhaustruct
    - gochecknoglobals
  exclusions:
    paths:
      - example_files/positive.go
      - example_files/negative.go
    paths-except:
      - example_files/positive.go
      - example_files/negative.go
